adding:
  dependencies:
    config:
      - node.type.faq
      - taxonomy.vocabulary.faq_categories
      - taxonomy.vocabulary.units
    module:
      - rabbit_hole
      - siteimprove
  permissions:
    - 'create faq content'
    - 'create terms in faq_categories'
    - 'create terms in units'
    - 'delete any faq content'
    - 'delete faq revisions'
    - 'delete own faq content'
    - 'delete terms in faq_categories'
    - 'delete terms in units'
    - 'edit any faq content'
    - 'edit own faq content'
    - 'edit terms in faq_categories'
    - 'edit terms in units'
    - 'enter faq revision log entry'
    - 'override faq authored by option'
    - 'override faq published option'
    - 'rabbit hole bypass taxonomy_term'
    - 'revert faq revisions'
    - 'use siteimprove'
    - 'view faq revisions'
removing:
  dependencies:
    config:
      - core.entity_view_display.fragment.region_item.default
      - core.entity_view_display.node.page.default
      - media.type.video
    module:
      - fragments
      - layout_builder
      - replicate_ui
