adding:
  dependencies:
    config:
      - node.type.faq
    module:
      - rabbit_hole
      - siteimprove
  permissions:
    - 'create faq content'
    - 'delete faq revisions'
    - 'delete own faq content'
    - 'edit any faq content'
    - 'edit own faq content'
    - 'enter faq revision log entry'
    - 'override faq published option'
    - 'rabbit hole bypass taxonomy_term'
    - 'revert faq revisions'
    - 'use siteimprove'
    - 'view faq revisions'
removing:
  dependencies:
    config:
      - core.entity_view_display.fragment.region_item.default
      - core.entity_view_display.node.page.default
    module:
      - fragments
      - layout_builder
