role_mappings:
  - collaborator|faculty
  - collaborator|staff
  - collaborator|affiliate
_core:
  default_config_hash: SJr1QVVTTte-gucsJ0GtimgsqKBVZWe6syXh5Y-Jl2I
member_of_attribute: 'urn:oid:1.3.6.1.4.1.5923.1.1.1.5'
