adding:
  third_party_settings:
    layout_builder:
      sections:
        -
          layout_id: layout_header
          layout_settings:
            label: Header
            context_mapping: {  }
            layout_builder_styles_style: {  }
          components:
            -
              uuid: 3ff442b4-712e-47e2-9c38-13f178f28440
              region: content
              configuration:
                id: system_breadcrumb_block
                label: Breadcrumbs
                label_display: '0'
                provider: system
                context_mapping: {  }
              weight: -10
              additional: {  }
            -
              uuid: 26e192ee-63a7-4cac-8865-674c89aa9063
              region: background
              configuration:
                id: 'field_block:node:article:field_image'
                label: 'Featured Image'
                label_display: '0'
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: entity_reference_entity_view
                  label: visually_hidden
                  settings:
                    view_mode: full__ultrawide
                  third_party_settings: {  }
              weight: 0
              additional: {  }
            -
              uuid: d75c28a9-d252-47df-86e8-206190ec5052
              region: content
              configuration:
                id: 'field_block:node:article:title'
                label: Title
                label_display: '0'
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: string
                  label: visually_hidden
                  settings:
                    link_to_entity: false
                  third_party_settings: {  }
              weight: -9
              additional: {  }
          third_party_settings: {  }
        -
          layout_id: layout_onecol
          layout_settings:
            label: Content
            context_mapping: {  }
          components:
            -
              uuid: bf4bf51c-26f8-4bbf-807f-708722bb4875
              region: content
              configuration:
                id: 'extra_field_block:node:article:content_moderation_control'
                label_display: '0'
                context_mapping:
                  entity: layout_builder.entity
              weight: 1
              additional: {  }
            -
              uuid: 026a4bb8-3434-4615-9211-93eb7a12ee2d
              region: content
              configuration:
                id: 'extra_field_block:node:article:article_created_date'
                label_display: '0'
                context_mapping:
                  entity: layout_builder.entity
              weight: 4
              additional: {  }
            -
              uuid: 1ff4f36b-9a8d-48bd-abbd-abefa66014f1
              region: content
              configuration:
                id: 'field_block:node:article:field_article_source_org'
                label_display: '0'
                context_mapping:
                  entity: layout_builder.entity
                formatter:
                  type: string
                  label: hidden
                  settings:
                    link_to_entity: false
                  third_party_settings: {  }
              weight: 6
              additional: {  }
            -
              uuid: 8c17705e-7015-4555-bee3-1d482b839802
              region: content
              configuration:
                id: 'field_block:node:article:field_article_source_link'
                label_display: '0'
                context_mapping:
                  entity: layout_builder.entity
                formatter:
                  type: link
                  label: hidden
                  settings:
                    trim_length: 80
                    url_only: false
                    url_plain: false
                    rel: ''
                    target: ''
                  third_party_settings: {  }
              weight: 7
              additional: {  }
            -
              uuid: e11264d2-f469-41f9-ae04-db2ce33883fa
              region: content
              configuration:
                id: 'field_block:node:article:body'
                label_display: '0'
                context_mapping:
                  entity: layout_builder.entity
                formatter:
                  type: text_default
                  label: hidden
                  settings: {  }
                  third_party_settings: {  }
              weight: 8
              additional: {  }
            -
              uuid: 6dea8df6-16b2-47ef-b6fd-c8a1b9922758
              region: content
              configuration:
                id: 'extra_field_block:node:article:links'
                label_display: '0'
                context_mapping:
                  entity: layout_builder.entity
              weight: 9
              additional: {  }
            -
              uuid: a0aa4574-dd5c-460d-befb-8eebabd8b817
              region: content
              configuration:
                id: 'field_block:node:article:field_article_author'
                label: 'Article Authors'
                label_display: '0'
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: entity_reference_label
                  label: inline
                  settings:
                    link: true
                  third_party_settings: {  }
              weight: 5
              additional: {  }
          third_party_settings: {  }
  hidden:
    entity_print_view_epub: true
    entity_print_view_pdf: true
    entity_print_view_word_docx: true
removing:
  third_party_settings:
    layout_builder:
      sections:
        -
          layout_id: layout_header
          layout_settings:
            label: Header
            context_mapping: {  }
            layout_builder_styles_style: {  }
          components:
            3ff442b4-712e-47e2-9c38-13f178f28440:
              uuid: 3ff442b4-712e-47e2-9c38-13f178f28440
              region: content
              configuration:
                id: system_breadcrumb_block
                label: Breadcrumbs
                label_display: '0'
                provider: system
                context_mapping: {  }
              weight: -10
              additional: {  }
            26e192ee-63a7-4cac-8865-674c89aa9063:
              uuid: 26e192ee-63a7-4cac-8865-674c89aa9063
              region: background
              configuration:
                id: 'field_block:node:article:field_image'
                label: 'Featured Image'
                label_display: '0'
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: entity_reference_entity_view
                  label: visually_hidden
                  settings:
                    view_mode: full__ultrawide
                  third_party_settings: {  }
              weight: 0
              additional: {  }
            d75c28a9-d252-47df-86e8-206190ec5052:
              uuid: d75c28a9-d252-47df-86e8-206190ec5052
              region: content
              configuration:
                id: 'field_block:node:article:title'
                label: Title
                label_display: '0'
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: string
                  label: visually_hidden
                  settings:
                    link_to_entity: false
                  third_party_settings: {  }
              weight: -9
              additional: {  }
          third_party_settings: {  }
        -
          layout_id: layout_onecol
          layout_settings:
            label: Content
            context_mapping: {  }
          components:
            bf4bf51c-26f8-4bbf-807f-708722bb4875:
              uuid: bf4bf51c-26f8-4bbf-807f-708722bb4875
              region: content
              configuration:
                id: 'extra_field_block:node:article:content_moderation_control'
                label_display: '0'
                context_mapping:
                  entity: layout_builder.entity
              weight: 1
              additional: {  }
            026a4bb8-3434-4615-9211-93eb7a12ee2d:
              uuid: 026a4bb8-3434-4615-9211-93eb7a12ee2d
              region: content
              configuration:
                id: 'extra_field_block:node:article:article_created_date'
                label_display: '0'
                context_mapping:
                  entity: layout_builder.entity
              weight: 4
              additional: {  }
            1ff4f36b-9a8d-48bd-abbd-abefa66014f1:
              uuid: 1ff4f36b-9a8d-48bd-abbd-abefa66014f1
              region: content
              configuration:
                id: 'field_block:node:article:field_article_source_org'
                label_display: '0'
                context_mapping:
                  entity: layout_builder.entity
                formatter:
                  type: string
                  label: hidden
                  settings:
                    link_to_entity: false
                  third_party_settings: {  }
              weight: 6
              additional: {  }
            8c17705e-7015-4555-bee3-1d482b839802:
              uuid: 8c17705e-7015-4555-bee3-1d482b839802
              region: content
              configuration:
                id: 'field_block:node:article:field_article_source_link'
                label_display: '0'
                context_mapping:
                  entity: layout_builder.entity
                formatter:
                  type: link
                  label: hidden
                  settings:
                    trim_length: 80
                    url_only: false
                    url_plain: false
                    rel: ''
                    target: ''
                  third_party_settings: {  }
              weight: 7
              additional: {  }
            e11264d2-f469-41f9-ae04-db2ce33883fa:
              uuid: e11264d2-f469-41f9-ae04-db2ce33883fa
              region: content
              configuration:
                id: 'field_block:node:article:body'
                label_display: '0'
                context_mapping:
                  entity: layout_builder.entity
                formatter:
                  type: text_default
                  label: hidden
                  settings: {  }
                  third_party_settings: {  }
              weight: 8
              additional: {  }
            6dea8df6-16b2-47ef-b6fd-c8a1b9922758:
              uuid: 6dea8df6-16b2-47ef-b6fd-c8a1b9922758
              region: content
              configuration:
                id: 'extra_field_block:node:article:links'
                label_display: '0'
                context_mapping:
                  entity: layout_builder.entity
              weight: 9
              additional: {  }
            a0aa4574-dd5c-460d-befb-8eebabd8b817:
              uuid: a0aa4574-dd5c-460d-befb-8eebabd8b817
              region: content
              configuration:
                id: 'field_block:node:article:field_article_author'
                label: 'Article Authors'
                label_display: '0'
                provider: layout_builder
                context_mapping:
                  entity: layout_builder.entity
                  view_mode: view_mode
                formatter:
                  type: entity_reference_label
                  label: inline
                  settings:
                    link: true
                  third_party_settings: {  }
              weight: 5
              additional: {  }
          third_party_settings: {  }
