adding:
  third_party_settings:
    layout_builder:
      sections:
        -
          layout_settings:
            context_mapping: {  }
        -
          layout_settings:
            context_mapping: {  }
  hidden:
    entity_print_view_epub: true
    entity_print_view_pdf: true
    entity_print_view_word_docx: true
removing: {  }
