adding:
  dependencies:
    config:
      - field.field.node.person.field_person_territory
    module:
      - options
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            config_split_sequence_5o5ediqcop7kgjj:
              weight: -8
            config_split_sequence_3bk1mb2ut210l4lb:
              uuid: 69dd1e67-4c47-4b9d-9bce-5e0cfb8d92c6
              region: first
              configuration:
                label_display: '0'
                context_mapping:
                  entity: layout_builder.entity
                id: 'field_block:node:person:field_person_territory'
                formatter:
                  label: above
                  settings: {  }
                  third_party_settings: {  }
                  type: list_default
              additional: {  }
              weight: -7
  content:
    field_person_hometown:
      weight: 12
      label: above
      settings:
        link_to_entity: false
      third_party_settings: {  }
      type: string
      region: content
    field_person_territory:
      weight: 11
      label: above
      settings: {  }
      third_party_settings: {  }
      type: list_default
      region: content
  hidden:
    entity_print_view_epub: true
    entity_print_view_pdf: true
    entity_print_view_word_docx: true
    field_person_types: true
removing:
  third_party_settings:
    layout_builder:
      sections:
        -
          components:
            config_split_sequence_5o5ediqcop7kgjj:
              weight: 3
  content:
    field_person_types:
      type: entity_reference_label
      weight: 11
      region: content
      label: inline
      settings:
        link: false
      third_party_settings: {  }
  hidden:
    field_person_hometown: true
