adding:
  dependencies:
    module:
      - content_translation
  third_party_settings:
    content_translation:
      enabled: false
      bundle_settings:
        untranslatable_fields_hide: '1'
removing: {  }
