adding:
  url:
    prefixes:
      ar: ar
      de: de
      es: es
      fa: fa
      fil: fil
      fr: fr
      km: km
      ku: ku
      ms: ms
      pl: pl
      pt: pt
      ro: ro
      ru: ru
      tr: tr
      uk: uk
      zh-hans: zh-hans
    domains:
      ar: ''
      de: ''
      es: ''
      fa: ''
      fil: ''
      fr: ''
      km: ''
      ku: ''
      ms: ''
      pl: ''
      pt: ''
      ro: ''
      ru: ''
      tr: ''
      uk: ''
      zh-hans: ''
removing: {  }
