adding:
  permissions:
    - 'create terms in writing_collection'
    - 'create writing content'
    - 'delete own writing content'
    - 'delete writing revisions'
    - 'edit any writing content'
    - 'edit own writing content'
    - 'edit terms in writing_collection'
    - 'enter writing revision log entry'
    - 'override writing published option'
    - 'revert writing revisions'
    - 'view writing revisions'
removing: {  }
