session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    ar: ar
    zh-hans: zh-hans
    km: km
    fil: fil
    fr: fr
    de: de
    ku: ku
    ms: ms
    fa: fa
    pl: pl
    pt: pt
    ro: ro
    ru: ru
    es: es
    tr: tr
    uk: uk
  domains:
    en: ''
    ar: ''
    zh-hans: ''
    km: ''
    fil: ''
    fr: ''
    de: ''
    ku: ''
    ms: ''
    fa: ''
    pl: ''
    pt: ''
    ro: ''
    ru: ''
    es: ''
    tr: ''
    uk: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
