uids_base.settings:
  type: config_object
  label: 'UIDS Base Theme settings.'
  mappings:
    header_type:
      type: mapping
      label: 'Header type'
      mapping:
        'header--primary':
          type: string
          label: 'Iowa'
        'header--secondary':
          type: string
          label: 'College'
        'header--tertiary':
          type: string
          label: 'Department'
    header_nav:
      type: mapping
      label: 'Header navigation type'
      mapping:
        'nav--toggle':
          type: string
          label: 'Toggle'
        'nav--horizontal':
          type: string
          label: 'Horizontal'
    header_sticky:
      type: integer
      label: 'Sticky header'
