adding:
  dependencies:
    config:
      - node.type.book
      - taxonomy.vocabulary.book_tags
    module:
      - book
      - siteimprove
  permissions:
    - 'add content to books'
    - 'create book content'
    - 'create terms in book_tags'
    - 'delete book revisions'
    - 'delete own book content'
    - 'edit any book content'
    - 'edit own book content'
    - 'edit terms in book_tags'
    - 'override book published option'
    - 'revert book revisions'
    - 'use siteimprove'
    - 'view book revisions'
removing: {  }
