header:
  type: header--primary
  nav_style: nav--toggle
  sticky: 1
layout:
  container: page__container
branding:
  legacy: 0
_core:
  default_config_hash: SKh8qzs6ODRGNkpsYQY088B2hKfLc1qn6WWKs6NQ8fo
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: true
favicon:
  use_default: true
