adding:
  dependencies:
    config:
      - node.type.book
      - taxonomy.vocabulary.season
      - taxonomy.vocabulary.series
      - taxonomy.vocabulary.subjects
    module:
      - siteimprove
  permissions:
    - 'create book content'
    - 'create terms in season'
    - 'create terms in series'
    - 'create terms in subjects'
    - 'delete any book content'
    - 'delete book revisions'
    - 'delete own book content'
    - 'edit any book content'
    - 'edit own book content'
    - 'edit terms in season'
    - 'edit terms in series'
    - 'edit terms in subjects'
    - 'enter book revision log entry'
    - 'override book published option'
    - 'revert book revisions'
    - 'use siteimprove'
    - 'view book revisions'
removing: {  }
