title: Documentation
description: Documentation for University of Iowa Drupal 8 based sites.

# Aux links for the upper right navigation
aux_links:
  "University of Iowa":
    - "//uiowa.edu"

remote_theme: pmarsceill/just-the-docs
